"""Change name of field in Email model

Revision ID: 2d2ca3d83bab
Revises: 90e9623fc23b
Create Date: 2022-10-17 21:56:41.914294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2ca3d83bab'
down_revision = '90e9623fc23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('uq_emails_mail', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_emails_email'), ['email'])
        batch_op.drop_column('mail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_emails_email'), type_='unique')
        batch_op.create_unique_constraint('uq_emails_mail', ['mail'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
