"""Remove email field

Revision ID: 302c80897131
Revises: 1ffeae2aa43e
Create Date: 2022-10-14 18:11:36.124620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302c80897131'
down_revision = '1ffeae2aa43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
