"""Edit imports

Revision ID: 62f51df5de97
Revises: c04e45dfa8ea
Create Date: 2022-10-17 16:27:56.599011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f51df5de97'
down_revision = 'c04e45dfa8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tags_name'), ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tags_name'), type_='unique')

    # ### end Alembic commands ###
