"""edit relationship btwn tag and note

Revision ID: 078282596d1a
Revises: 72d3d8d77182
Create Date: 2022-09-18 17:52:18.189486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078282596d1a'
down_revision = '72d3d8d77182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
