"""note tag

Revision ID: 2230a36b1717
Revises: 92aad59e35b3
Create Date: 2022-09-17 00:42:39.036180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2230a36b1717'
down_revision = '92aad59e35b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
