"""edit relationship btwn tag and note

Revision ID: 33714b715511
Revises: 078282596d1a
Create Date: 2022-09-18 17:59:50.880821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33714b715511'
down_revision = '078282596d1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
