"""change relationship btwn tag and note

Revision ID: 72d3d8d77182
Revises: 945494fac9ea
Create Date: 2022-09-18 17:40:44.251150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d3d8d77182'
down_revision = '945494fac9ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
