"""add onedelete cascade

Revision ID: 92aad59e35b3
Revises: cb4d941d284f
Create Date: 2022-09-17 00:40:49.226215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92aad59e35b3'
down_revision = 'cb4d941d284f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_details_student_id_fkey', 'contact_details', type_='foreignkey')
    op.create_foreign_key(None, 'contact_details', 'contacts', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_details', type_='foreignkey')
    op.create_foreign_key('contact_details_student_id_fkey', 'contact_details', 'contacts', ['student_id'], ['id'])
    # ### end Alembic commands ###
