"""change tags in notes to json

Revision ID: 945494fac9ea
Revises: 0ebd5854c628
Create Date: 2022-09-18 14:46:29.859421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945494fac9ea'
down_revision = '0ebd5854c628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tags', sa.JSON(), nullable=True))
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('tags', 'tags')
    # ### end Alembic commands ###
